services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=oc-user
      - POSTGRES_PASSWORD=this-is-a-strong-password
      - POSTGRES_DB=oc-db
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - application-network

volumes:
  db_data:

networks:
  application-network: